name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on:
      - ubuntu-latest
      - macos-latest

    container: httptoolkit/act-build-base:v3.0.1

    strategy:
      matrix:
        node-version: [v20.x, v20.11.1, v22.x, '*']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - name: Install and start usbmuxd
        # This isn't actually usable - we can't access USBs - but it's enough to give us
        # a socket file & daemon to do very basic testing against.
        run: sudo apt update && sudo apt install -y usbmuxd && sudo usbmuxd

      - run: npm install
      - run: npm test